steps:
  - script: python -m pip install codacy-coverage codecov
    displayName: 'Install Coverage Reporters'

  - script: coverage combine
    displayName: 'Combine coverage file'

  - script: |
      coverage combine
      coverage xml -o coverage.xml
    displayName: 'Build Coverage Report'

  - script: python -m codecov
    env:
      CODECOV_TOKEN: $(CODECOV_TOKEN)
    displayName: 'Send Coverage Report'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura' # Options: cobertura, jaCoCo
    summaryFileLocation: 'coverage.xml'
